enum VARS {
  API_CONSOLE = 'API-консолька',
  EMAIL = 'email',
  SUBLOGIN_ENG = 'sublogin',
  PASSWORD_ENG = 'password',
  LOGIN = 'Логин',
  SUBLOGIN = 'Сублогин',
  PASSWORD = 'Пароль',
  ENTER = 'Войти',
  GITHUB_NAME = '@blackraydev',
  GITHUB_LINK = 'https://github.com/blackraydev',
  FAILED_LOGIN = 'Вход не вышел',
  OPTIONAL = 'Опционально',
  LOGOUT = 'Выйти',
  EXECUTE = 'Выполнить',
  COPY = 'Скопировать',
  DELETE = 'Удалить',
  SEND = 'Отправить',
  FORMAT = 'Форматировать',
  REQUEST = 'Запрос',
  RESPONSE = 'Ответ',
  EMPTY = 'EMPTY',
  COPIED = 'Скопировано',
}

export default VARS;
